AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs18.x
    CodeUri: ../functions/
    Handler: handler.handler
    Environment:
      Variables:
        DYNAMODB_TABLE: !Ref DynamoDbTable

Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Ref AWS::StackName

  ListFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref DynamoDbTable
      Events:
        List:
          Type: Api
          Properties:
            Path: /list
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - list/handler.ts

  AddFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref DynamoDbTable
      Events:
        Add:
          Type: Api
          Properties:
            Path: /add
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - add/handler.ts

Outputs:
  ListEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/list/"
  AddEndpoint:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/add/"
